// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhBdZP_Vmys7dZVp-uUtydo9LVHstLzKY',
    appId: '1:381615954985:web:794280fda996b17bbed038',
    messagingSenderId: '381615954985',
    projectId: 'kannada-app-cd17b',
    authDomain: 'kannada-app-cd17b.firebaseapp.com',
    storageBucket: 'kannada-app-cd17b.firebasestorage.app',
    measurementId: 'G-9W3S74WGZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoT_yIUbAlpyhgxGtMDEP_LHcI98mVJSA',
    appId: '1:381615954985:android:f9c1d7cc9e1b1e1cbed038',
    messagingSenderId: '381615954985',
    projectId: 'kannada-app-cd17b',
    storageBucket: 'kannada-app-cd17b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKdaE6AaCXrvO-IQE3Qt_zZfOn6aZDJ-w',
    appId: '1:381615954985:ios:6fb8225bc3024409bed038',
    messagingSenderId: '381615954985',
    projectId: 'kannada-app-cd17b',
    storageBucket: 'kannada-app-cd17b.firebasestorage.app',
    iosBundleId: 'com.suviko.learnkannada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKdaE6AaCXrvO-IQE3Qt_zZfOn6aZDJ-w',
    appId: '1:381615954985:ios:c9acf98544ae3386bed038',
    messagingSenderId: '381615954985',
    projectId: 'kannada-app-cd17b',
    storageBucket: 'kannada-app-cd17b.firebasestorage.app',
    iosBundleId: 'com.example.learnKannada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhBdZP_Vmys7dZVp-uUtydo9LVHstLzKY',
    appId: '1:381615954985:web:6b900ef072470d2ebed038',
    messagingSenderId: '381615954985',
    projectId: 'kannada-app-cd17b',
    authDomain: 'kannada-app-cd17b.firebaseapp.com',
    storageBucket: 'kannada-app-cd17b.firebasestorage.app',
    measurementId: 'G-3BFD8WB4EL',
  );
}
